import logging
from typing import Dict, List, Literal, Optional

import dspy

from core.config import master_llm_config as config
from practice.observation_trainer.schemas import (
    DescribeRequest,
    DescribeResponse,
    EvaluateRequest,
    EvaluateResponse,
    EvaluationSummary,
    HiddenDetailsSummary,
    ImageAnalysis,
    MissedDetail,
    RevealHiddenRequest,
    RevealHiddenResponse,
    TrainRequest,
    TrainResponse,
)

logger = logging.getLogger(__name__)


class ObservationTrainerError(Exception):
    """Base exception for all observation trainer failures."""


class GenerationError(ObservationTrainerError):
    """Raised when a DSPy pipeline fails to produce content."""


class ImageDescriber(dspy.Signature):
    """
    You are an expert visual analyst. Given an image, produce a comprehensive,
    structured description covering all observable elements — subjects, setting,
    colors, text, spatial relationships, lighting, mood, and subtle details.
    Be thorough and objective. Do not infer beyond what is visible.
    """

    image: str = dspy.InputField(
        description="Image input — accepts a URL, base64-encoded string, or file path."
    )
    scenario_context: Optional[str] = dspy.InputField(
        default=None,
        description="Optional context about the image domain (e.g., 'crime scene', 'medical scan') to guide description focus.",
    )

    detailed_description: str = dspy.OutputField(
        description="A thorough, structured textual description of everything visible in the image."
    )
    key_elements: List[str] = dspy.OutputField(
        description="List of the most important visual elements identified (subjects, objects, text, etc.)."
    )
    subtle_details: List[str] = dspy.OutputField(
        description="List of small or easily-overlooked details (background items, reflections, shadows, textures, etc.)."
    )


class ImageObservationEvaluator(dspy.Signature):
    """
    You are an expert observation trainer. Your role is to evaluate how well a
    user has observed an image. Compare their observations against the actual
    image description, assess the depth and accuracy of their observations, and
    rate their observation skills.

    IMPORTANT: Consider the training scenario when evaluating. A user training
    for crime scene investigation should be judged differently than one
    practicing art appreciation. The scenario defines what counts as 'good
    observation'.

    Focus on:
    - Accuracy of their claims (are they correct?)
    - Depth of observation (surface-level vs. detailed)
    - Coverage (main subjects vs. background/details)
    - Inference quality (reasonable deductions vs. assumptions)
    - Scenario relevance (did they notice what matters for their training goal?)
    """

    image: str = dspy.InputField(
        description="The image the user observed — URL, base64, or file path."
    )
    image_description: str = dspy.InputField(
        description="Ground-truth detailed description of what's actually in the image (generated by vision system)."
    )
    user_observations: str = dspy.InputField(
        description="What the user has reported observing in the image."
    )
    training_scenario: str = dspy.InputField(
        description="""
        The scenario or task the user is being trained on.
        Examples: 'Crime scene investigation', 'Medical radiology screening',
        'Art critique and analysis', 'Security surveillance monitoring',
        'Wildlife identification', 'Quality control inspection'.
        This defines what observation priorities are expected.
        """
    )
    context_category: Optional[str] = dspy.InputField(
        default=None,
        description="Category of the image (e.g., portrait, landscape, diagram, x-ray, photograph).",
    )

    accuracy_assessment: str = dspy.OutputField(
        description="Detailed assessment of how accurate the user's observations are against the ground truth."
    )
    scenario_relevance_assessment: str = dspy.OutputField(
        description="Assessment of whether the user noticed elements relevant to their specific training scenario."
    )
    observation_rating: Literal["Beginner", "Intermediate", "Advanced", "Expert"] = dspy.OutputField(
        description="Overall rating of the user's observation skill level."
    )
    score_out_of_10: int = dspy.OutputField(
        description="Numerical score from 1-10 based on completeness, accuracy, depth, and scenario relevance."
    )
    strengths: List[str] = dspy.OutputField(
        description="List of things the user observed well or correctly."
    )
    areas_for_improvement: List[str] = dspy.OutputField(
        description="List of observation habits or areas the user should work on."
    )
    scenario_specific_feedback: str = dspy.OutputField(
        description="Feedback tailored to the training scenario — what skills to develop for this specific task."
    )
    feedback_message: str = dspy.OutputField(
        description="Encouraging, constructive feedback message for the user."
    )


class HiddenDetailsRevealer(dspy.Signature):
    """
    You are a detail-spotting trainer. Given an image and what a user has
    already observed, identify important details, nuances, and elements that the
    user has likely missed. Present these in a structured, educational way to
    improve their observation skills over time.

    IMPORTANT: Prioritize details based on the training scenario. For a crime
    scene scenario, focus on evidence-related details. For art analysis, focus
    on composition, color, and technique. Always explain WHY each detail matters
    in the context of the user's training goal.

    Categorize missed details by type and explain why they matter.
    Do NOT repeat details the user already caught.
    """

    image: str = dspy.InputField(
        description="The image being analyzed — URL, base64, or file path."
    )
    image_description: str = dspy.InputField(
        description="Complete, detailed ground-truth description of what's in the image."
    )
    user_observations: str = dspy.InputField(
        description="What the user has already noticed in the image."
    )
    training_scenario: str = dspy.InputField(
        description="""
        The scenario or task the user is being trained on.
        This determines which missed details are most critical to highlight.
        Examples: 'Forensic evidence collection', 'Radiology abnormality detection',
        'Art composition analysis', 'Perimeter security assessment'.
        """
    )
    training_focus: Optional[str] = dspy.InputField(
        default=None,
        description="Specific area to focus on (e.g., body language, background, lighting, text, patterns, anomalies).",
    )

    missed_details: List[Dict[str, str]] = dspy.OutputField(
        description="""
        List of details the user missed. Each dict contains:
        - 'detail': The specific detail missed
        - 'category': Category like 'foreground', 'background', 'lighting', 'emotion', 'text', 'spatial', 'patterns', 'anomaly'
        - 'significance': Why this detail matters, especially in the context of the training scenario
        - 'scenario_priority': 'high', 'medium', or 'low' — how important this is for the user's training goal
        """
    )
    observation_score_if_these_noticed: int = dspy.OutputField(
        description="What the user's score would be if they had noticed these details (1-10)."
    )
    scenario_skill_gap: str = dspy.OutputField(
        description="Analysis of what observation skill the user is lacking for their specific training scenario."
    )
    training_tip: str = dspy.OutputField(
        description="A practical, scenario-specific tip to help the user notice similar details in future."
    )
    practice_exercise: str = dspy.OutputField(
        description="A suggested exercise or drill the user can do to improve this specific observation skill."
    )
    encouragement: str = dspy.OutputField(
        description="Positive, motivating message about improvement."
    )


class ObservationTrainerService:
    """Business layer wrapping the DSPy observation training pipelines."""

    def __init__(self) -> None:
        self.lm = dspy.LM(
            model=f"openai/{config['model_name']}",
            api_key=config['api_key'],
            api_base=config['api_base'],
            temperature=config.get('temperature', 0.3),
        )
        self.describer = dspy.Predict(ImageDescriber)
        self.evaluator = dspy.Predict(ImageObservationEvaluator)
        self.revealer = dspy.Predict(HiddenDetailsRevealer)

    @staticmethod
    def _build_missed_details(raw_items: List[object]) -> List[MissedDetail]:
        """
        Normalizes raw DSPy output into validated MissedDetail models.

        Args:
            raw_items (List[object]): Raw detail dictionaries from the LLM.

        Returns:
            List[MissedDetail]: Validated missed-detail models.
        """
        normalized: List[MissedDetail] = []
        for item in raw_items:
            if not isinstance(item, dict):
                continue
            priority = str(item.get("scenario_priority", "")).lower()
            if priority not in ("high", "medium", "low"):
                priority = "medium"
            normalized.append(
                MissedDetail(
                    detail=str(item.get("detail", "")),
                    category=str(item.get("category", "")),
                    significance=str(item.get("significance", "")),
                    scenario_priority=priority,
                )
            )
        return normalized

    async def describe(self, data: DescribeRequest) -> DescribeResponse:
        """
        Generates a structured ground-truth description of an image.

        Args:
            data (DescribeRequest): The validated image description request.

        Returns:
            DescribeResponse: The structured description of the image.

        Raises:
            GenerationError: If the vision pipeline fails to describe the image.
        """
        try:
            with dspy.context(lm=self.lm):
                result = self.describer(
                    image=data.image,
                    scenario_context=data.scenario_context,
                )
            logger.info("Described image: %s", data.image)
            return DescribeResponse(
                detailed_description=result.detailed_description,
                key_elements=result.key_elements,
                subtle_details=result.subtle_details,
            )
        except Exception as exc:
            logger.error("Image description failed for %s: %s", data.image, exc, exc_info=True)
            raise GenerationError(str(exc)) from exc

    async def evaluate(self, data: EvaluateRequest) -> EvaluateResponse:
        """
        Evaluates a user's observations against the ground truth of an image.

        Args:
            data (EvaluateRequest): The validated evaluation request.

        Returns:
            EvaluateResponse: The observation evaluation summary.

        Raises:
            GenerationError: If the evaluation pipeline fails.
        """
        try:
            with dspy.context(lm=self.lm):
                description = self.describer(
                    image=data.image,
                    scenario_context=data.context_category,
                )
                result = self.evaluator(
                    image=data.image,
                    image_description=description.detailed_description,
                    user_observations=data.user_observations,
                    training_scenario=data.training_scenario,
                    context_category=data.context_category,
                )
            logger.info("Evaluated observations for scenario: %s", data.training_scenario)
            return EvaluateResponse(
                accuracy_assessment=result.accuracy_assessment,
                scenario_relevance=result.scenario_relevance_assessment,
                rating=result.observation_rating,
                score=result.score_out_of_10,
                strengths=result.strengths,
                areas_for_improvement=result.areas_for_improvement,
                scenario_feedback=result.scenario_specific_feedback,
                feedback=result.feedback_message,
            )
        except Exception as exc:
            logger.error("Observation evaluation failed: %s", exc, exc_info=True)
            raise GenerationError(str(exc)) from exc

    async def reveal_hidden(self, data: RevealHiddenRequest) -> RevealHiddenResponse:
        """
        Reveals details the user likely missed, with scenario-tailored training tips.

        Args:
            data (RevealHiddenRequest): The validated reveal request.

        Returns:
            RevealHiddenResponse: The missed details and training guidance.

        Raises:
            GenerationError: If the reveal pipeline fails.
        """
        try:
            with dspy.context(lm=self.lm):
                description = self.describer(
                    image=data.image,
                    scenario_context=None,
                )
                result = self.revealer(
                    image=data.image,
                    image_description=description.detailed_description,
                    user_observations=data.user_observations,
                    training_scenario=data.training_scenario,
                    training_focus=data.training_focus,
                )
            logger.info("Revealed hidden details for scenario: %s", data.training_scenario)
            return RevealHiddenResponse(
                missed_details=self._build_missed_details(result.missed_details),
                potential_score=result.observation_score_if_these_noticed,
                skill_gap=result.scenario_skill_gap,
                training_tip=result.training_tip,
                practice_exercise=result.practice_exercise,
                encouragement=result.encouragement,
            )
        except Exception as exc:
            logger.error("Hidden-details reveal failed: %s", exc, exc_info=True)
            raise GenerationError(str(exc)) from exc

    async def run_training(self, data: TrainRequest) -> TrainResponse:
        """
        Runs the full observation training pipeline: describe, evaluate, and
        optionally reveal hidden details.

        Args:
            data (TrainRequest): The validated training request.

        Returns:
            TrainResponse: The image analysis, evaluation, and optional hidden details.

        Raises:
            GenerationError: If any step of the pipeline fails.
        """
        try:
            with dspy.context(lm=self.lm):
                desc_result = self.describer(
                    image=data.image,
                    scenario_context=data.context_category,
                )

                eval_result = self.evaluator(
                    image=data.image,
                    image_description=desc_result.detailed_description,
                    user_observations=data.user_observations,
                    training_scenario=data.training_scenario,
                    context_category=data.context_category,
                )

                hidden_summary = None
                if data.reveal_hidden:
                    reveal_result = self.revealer(
                        image=data.image,
                        image_description=desc_result.detailed_description,
                        user_observations=data.user_observations,
                        training_scenario=data.training_scenario,
                        training_focus=data.training_focus,
                    )
                    hidden_summary = HiddenDetailsSummary(
                        missed_items=self._build_missed_details(reveal_result.missed_details),
                        potential_score=reveal_result.observation_score_if_these_noticed,
                        skill_gap=reveal_result.scenario_skill_gap,
                        training_tip=reveal_result.training_tip,
                        practice_exercise=reveal_result.practice_exercise,
                        encouragement=reveal_result.encouragement,
                    )

            logger.info("Completed training run for scenario: %s", data.training_scenario)
            return TrainResponse(
                image_analysis=ImageAnalysis(
                    ground_truth_description=desc_result.detailed_description,
                    key_elements=desc_result.key_elements,
                    subtle_details=desc_result.subtle_details,
                ),
                evaluation=EvaluationSummary(
                    accuracy_assessment=eval_result.accuracy_assessment,
                    scenario_relevance=eval_result.scenario_relevance_assessment,
                    rating=eval_result.observation_rating,
                    score=eval_result.score_out_of_10,
                    strengths=eval_result.strengths,
                    areas_for_improvement=eval_result.areas_for_improvement,
                    scenario_feedback=eval_result.scenario_specific_feedback,
                    feedback=eval_result.feedback_message,
                ),
                hidden_details=hidden_summary,
                training_scenario=data.training_scenario,
            )
        except Exception as exc:
            logger.error("Training pipeline failed: %s", exc, exc_info=True)
            raise GenerationError(str(exc)) from exc
